import type { Metadata } from "next";
import "./globals.css";
import Script from "next/script";

export const metadata: Metadata = {
  title: "Code Biosis",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
 

  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
      <Script
          async
          src="https://www.googletagmanager.com/gtag/js?id=G-ELJDDL4Z88"
          strategy="afterInteractive"
        />
        <Script id="google-analytics" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'G-ELJDDL4Z88');
          `}
        </Script>

      </head>
      <body>
        
        {children}</body>
    </html>
  );
}
